[package]
name = "iota_oracle_system_state"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x0ccf40aaaa7cc933a4f81320ca1c8ae20fff090f190431e7afb9e248ae216e3a"
# license = "SPDX-License-Identifier: AGPLv3"
# authors = [""]

[dependencies]
iota_oracle_validator_caps = { local = "../oracle_validator_caps_testnet" }

[addresses]
iota_oracle_system_state = "0x0ccf40aaaa7cc933a4f81320ca1c8ae20fff090f190431e7afb9e248ae216e3a"
