[package]
name = "iota_oracle_scheduler"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x5ab8afb6ac37a551506eac2db9c5a3c2e454c6fadbff0a550a523b12c6e24f51"

[dependencies]
iota_oracle_tasks = { local = "../oracle_tasks_devnet" }

[addresses]
iota_oracle_scheduler = "0x5ab8afb6ac37a551506eac2db9c5a3c2e454c6fadbff0a550a523b12c6e24f51"
